### ISSUE TITLE
whisper not working - whisper.cpp not downloading correctly main.exe missing

### ISSUE THREAD

**Issue by santiyounger** [JonnyBurger/template-whisper-subtitle#1]
Hey thanks for sharing this project, I'd really like to use this, but when I can't get whisper to download and work correctly:

I run this command as instructed in the README.md 

`node sub.mjs`

it downloads but it seems like a `main.exe`  is not there

it creates this, folder with just this one file `whisper.cpp` > `ggml-medium.en.bin`

![image](https://github.com/remotion-dev/template-tiktok/assets/51902730/2a1d0552-c5a1-4a9f-a497-7f749030c518)

but if I understand this error message correctly, there should be a `main.exe` that didn't download. I'm trying to find the .exe on Hugging Face or GitHub but I can't figure out how to download it from anywhere. I'm not sure what to do; I've been stuck on this for an hour lol.

<details><summary>Here's the error message I get when it downloads after using "node sub.mjs"</summary>
<p>
<code>
Downloaded 1521640597 of 1533774781 bytes (99.21%)
Downloaded 1532139159 of 1533774781 bytes (99.89%)
Downloaded 1533774781 of 1533774781 bytes (100.00%)
Extracting audio from file sample-video-2.mp4
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: spawn D:\Dropbox\Projects\code-2024\captions-v1\whisper.cpp\main.exe ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn D:\\Dropbox\\Projects\\code-2024\\captions-v1\\whisper.cpp\\main.exe',
  path: 'D:\\Dropbox\\Projects\\code-2024\\captions-v1\\whisper.cpp\\main.exe',
  spawnargs: [
    '-f',
    'D:\\Dropbox\\Projects\\code-2024\\captions-v1\\temp\\sample-video-2.wav',
    '--output-file',
    'D:\\Dropbox\\Projects\\code-2024\\captions-v1\\tmp',
    '--output-json',
    '--max-len',
    1,
    '-ojf',
    '--dtw',
    'medium.en',
    '-m',
    'D:\\Dropbox\\Projects\\code-2024\\captions-v1\\whisper.cpp\\ggml-medium.en.bin'
  ]
}

Node.js v20.9.0
PS D:\Dropbox\Projects\code-2024\captions-v1>
</code>
</p>
</details> 

I'm in windows 11, please let me know if you need any more details. I'm trying to install this template from scratch so all I did before this is `npx create-video@latest` and then choose the tiktok template. I'm in Vs Code I tried to run this from VS code's terminal, as well as separately from window's powershell

Thank you, and thanks again for sharing this, can't wait to try it!

**Comment by santiyounger** [comment]
I did more research and seems like building the .exe in windows is very complicated and I haven't been able to achieve it.

Would it be possible to use OpenAI Whisper's API instead, I tried to achieve this but I'm not sure what's the correct format of a transcript that I'm looking, a bit of guidance on this would be much appreciated thanks!

**Comment by JonnyBurger** [comment]
@santiyounger We don't have a resource for that unfortunately, but  we fixed the Windows bug now, if you run `npx remotion upgrade` and delete the `whisper.cpp` folder that will work now!

**Comment by santiyounger** [comment]
awesome thank you @JonnyBurger that's incredible appreciate it!
